from discord.ext import commands
import random
class GetUsername(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
    @commands.command()
    async def soru(self, ctx, member: commands.MemberConverter = None):
        r_text = [
    " *Telefonunda en son aradığın şey neydi?* ",
    " *Birisi kız arkadaşın / erkek arkadaşından ayrılmak için sana 1 milyon tl önerseydi, yapar mıydın?* ",
    " *Yerden bir şeyi alıp hiç yedin mi?* ",
    " *Yılan, kurbağa gibi şeylerden yemek zorunda kaldın mı?* ",
    " *Bir gün karşı cins olarak uyanırsan, ilk yapacağın şey nedir?* ",
    " *Büyüyen hayali bir arkadaşınız var mıydı?* ",
    " *En kötü alışkanlığınız nedir?* ",
    " *Banyoda şarkı söyler misin?* ",
    " *Toplumda en utanç verici anınız neydi?* ",
    " *Aynada kendinle hiç konuştun mu?* ",
    " *Web geçmişinizi, birileri görürse utanacağınız şey ne olurdu?* ",
    " *Uykunda konuşur musun?* ",
    " *Özelden sana yazan birine son attığın mesaj neydi?* ",
    " *Söylediğiniz veya yaptığınız bir şeyi silmek için zamanda geriye gidebilseydiniz, bu ne olurdu?* ",
    " *Yeniden doğmuş olsaydın, hangi yüz yılda doğmak isterdin?* ",
    " *Hala yaptığın en çocukça şey nedir?* ",
    " *Hangi çocuk filmini tekrar tekrar izleyebilirsin?* ",
    " *Saçma takma adların var mı?* ",
    " *Telefonunuzda hangi uygulamada en çok zaman harcıyorsunuz?* ",
    " *Tek bir oturuşta yediğin en çok yemek ne?* ",
    " *Tek başınayken dans ediyor musun?* ",
    " *Karanlıktan korkar mısın?* ",
    " *Bütün gün evdeysen ne yapardın?* ",
    " *Günde kaç öz çekim yapıyorsunuz?* ",
    " *En son ne zaman dişlerini fırçaladın?* ",
    " *En sevdiğin pijamalar neye benziyor?* ",
    " *Yapmaman gereken bir şeyi yaparken hiç yakalandın mı? Eğer yakalandıysan yaptığın şey ne?* ",
    " *Vücudunun hangi bölümünü seviyorsun, hangi kısmından nefret ediyorsun?* ",
    " *Hiç bitlendin mi?* ",
    " *Pantolonunu moda için hiç kestin mi?* ",
    " *Tabağını yalıyor musun?* ",
    " *Kimsenin senin hakkında bilmediği bir şey varmı?* ",
    " *Eğer bu gruptaki herkesi yanan bir binadan kurtarmaya çalışıyor olsaydın ve birini geride bırakmak zorunda kalırsan, kimi geride bırakırdın?* ",
    " *Telefonda aradığın son şey neydi?* ",
    " *Hiç asansörde gaz kaçırdın mı?* ",
    " *Banyodayken yanlışlıkla hiç kimse içeri girdi mi?* ",
    " *Bir günlüğüne karşı cins olsan ne yapardın?* ",
    " *Hayatınızda bir şey değiştirebilseydiniz, ne olurdu?* ",
    " *En büyük pişmanlığın nedir?* ",
    " *Kimsenin bulamadığı kötü bir şey yaptınız mı?* ",
    " *Telefonunuzdaki en utanç verici fotoğraf hangisidir?* ",
    " *Şimdiye kadar gördüğünüz en korkunç rüya nedir?* ",
    " *Çorabını değiştirirken ayağını koklar mısın?* ",
    " *Bir ilişkinizdeki en büyük korkunuz nedir?* ",
    " *Hiç yaşınız hakkında yalan söylediniz mi?* ",
    " *En komik ilk randevunuz neydi?* ",
    " *En garip alışkanlığın nedir?* ",
    " *Kaç tane çocuk sahibi olmak istersiniz?* ",
    " *Çocukluktaki lakabın neydi?* ",
    " *En sevdiğiniz yemek nedir?* ",
    " *Hayalindeki meslek ne?* ",
    " *Bir adada 3 gün sıkışıp kalırsan, ne yaparsın?* ",
    " *En sevdiğiniz kişi kimlerdir ve neden?* ",
    " *İlk görüşte aşka inanır mısın?* ",
    " *Aşka inanıyor musunuz?* ",
    " *Şansınız olursa hangi ülkede yaşamak istersiniz?* ",
    " *Hayalinizdeki düğün nedir?* ",
    " *Şimdiye dek yaşadığınız en garip rüyayı açıklayabilir misiniz?* ",
    " *En büyük pişmanlığın nedir?* ",
    " *Saçını yıkamadan en uzun ne kadar süre bekledin?* ",
    " *Herhangi bir ünlü ile evlenseydin, kim olurdu?* ",
    " *Kaç tane erkek/kız arkadaşın oldu?* ",
    " *Şu an sevgilin varmı?* ",
    " *Şu an sevdiğin varmı?* ",
    " *Vücudunun hangi bölümünü seviyorsun, hangi kısmından nefret ediyorsun?* ",
    " *Aynada kendine hayran hayran bakar mısın?* ",
    " *Hayran olduğun ünlü kim?* ",
    " *Sevdiğiniz birinin önünde söylediğiniz veya yaptığınız en utanç verici şey nedir?* ",
    " *Hayallerinizdeki insanla evleneceksin denilse, telefonsuz bir yıl geçirir miydiniz?* ",
    " *Hayatınızın geri kalanında sadece tek bir saç modeli yapabilseydin, kıvırcık saçları mı yoksa düz saçları mı seçerdin?* ",
    " *Senden daha kısa biriyle çıkar mısın?* ",
    " *Aynaya uzun süre bakmak seni korkutur mu?* ",
    " *Sevgilinle ilgili yaptığın en utanç verici şey nedir?* ",
    " *Issız bir adada bu gruptan kimin mahsur kalmasını isterdiniz?* ",
    " *Hiç terk edildin mi? Bunun nedeni neydi?* ",
    " *Yapabilseydin kendin üzerinde değiştirebileceğin bir fiziksel özellik nedir?* ",
    " *Hayatında yaptığın en doğru şey?* ",
    " *Doğa üstü bi yetenek edinebilsen bu ne olurdu?* ",
    " *Birine sevdiğini nasıl belli edersin?* ",
    " *Çocukluğun nasıl geçti?* ",
    " *Bi kelime üret ve ne anlama geldiğini söyle* ",
    " *Mucizelere inanır mısın?* ",
    " *Seni en çok ne sinirlendirir?* ",
    " *Hayatta unutmadığın biri var mı?* ",
    " *Dövme yaptırmak istesen ne yaptırırdın?* ",
    " *Eğer bir zaman makinen olsaydı ve geçmişe gidip yaptığın tek bir şeyi silebilecek olsaydın, neyi silerdin?* ",
    " *Seni ve sevgilini esir alsalar, ya onun canı ya senin canın deseler kimi seçerdin?* ",
    " *Şekil değiştirme özelliğin olsaydı ilk neye dönüşürdün?* ",
    " *Hiç sevgilin oldu mu?* ",
    " *İnsanlardan uzak kalmayı sever misin?* ",
    " *Gece mi Gündüz mü?* ",
    " *İnsanların düşüncelerini okuyabilseydin ilk kiminkini okurdun?* ",
    " *Senin için çok özel birine büyük bir yalan söyledin mi?* ",
    " *Bu gruptan biriyle çıkmak istesen o kim olurdu?* ",
    " *Sana göre bu gruptaki kim seni daha çok seviyor?* ",
    " *Yanlız kaldığında ne tür hayaller kurarsın?* ",
    " *Yağmurlu bir sonbahar akşamı mı yoksa karlı bir kış gecesimi?* ",
    " *Bu grupta kendini kime daha yakın hissediyorsun?* ",
    " *Bu gruptaki herkes tehlikede! Sadece bir kişiyi kurtarma şansın var. Diğer kalanlar %40 ihtimalle hayatta kalacaklar. Kimi kurtarırsın?* ",
    " *Hiç sana aşkını itiraf eden birini reddettinmi? Ettiysen ismi ne?* ",
    " *Sevgili mi kanka mı?* ",
    " *İtiraf Vakti! Hiç daha önce birini aldattı mı?* ",
    " *İtiraf Vakti! Hiç özelini başka biriyle paylaştın mı?* ",
    " *İtiraf Vakti! Gece gizlice düşündüğün biri varmı? Varsa adı ne?* ",
    " *İtiraf Vakti! Daha önce hiç aşkını kalbine gömdün mü?* ",
    " *İtiraf Vakti! Bu grupta sana aşık olabilecek kimler var?* ",
    " *İtiraf Vakti! Hayalindeki sevgili için en yakın arkadaşından vazgeçermisin?* ",
    " *İtiraf Vakti! Bu grupta fizik ve çekicilik olarak en fazla beğendiğin kişi kim?* ",
    " *Kapana Kısıldın! Çabuk cevap ver! Aileni terkedip en fazla arzuladığın kişinin yanına gitmek mi yoksa 40'ına kadar aile evinde oturmak mı?* ",
    " *Kapana Kısıldın! Başına silah doğrultulmuş ve ya senin canın yada ailenin canı. Hangisini seçersin?* ",
    " *Kapana Kısıldın! Çirkin ama zengin biriyle mi çıkmak istersin yada güzel ama fakir biriyle mi?* ",
    " *Joker Soru! Bu soruya denk gelmek senin çok şanslı olduğunu gösterir. İşte sana sorum:\nAşk mı Para mı?* "
]
        sor=random.choice(r_text)
        if member:
            await ctx.send(f'{member.mention} {sor}')
        else:
            if ctx.message.reference:
                replied_message = await ctx.fetch_message(ctx.message.reference.message_id)
                user = replied_message.author
                await ctx.send(f'{user.mention} {sor}')
            else:
                await ctx.send(f'{ctx.author.mention} {sor}')
    @commands.command()
    async def zorsoru(self, ctx, member: commands.MemberConverter = None):
        rzor = [
    " *Biriyle çıkarken yaptığın en utanç verici şey neydi?* ",
    " *Toplu taşıma araçlarında yaptığın en çılgınca şey neydi?* ",
    " *Şimdiye kadar bir başkasına söylediğin en acımasızca şey neydi?* ",
    " *Hiçbir sonucu olmayacağını bilsen ne yapmak isterdin?* ",
    " *Arkadaşlarınla yapmayı sevdiğin ama sevgilinin önünde asla yapmayacağın şey nedir?* ",
    " *Bu hayatta en çok kimi kıskanıyorsun?* ",
    " *Aşk için her şeyi yaparım ama “bunu” yapmam dediğin şey nedir?* ",
    " *Çeşitli batıl inançların var mı? Varsa onlar neler?* ",
    " *Sevdiğini itiraf etmekten utandığın film hangisidir?* ",
    " *En utan verici kişisel bakım alışkanlığın nedir?* ",
    " *Kimsenin bilmeyeceği garanti olsa kimi öldürmek isterdin?* ",
    " *Başkası için aldığın en ucuz hediye nedir?* ",
    " *Hiç toplum içinde çıplak kaldın mı?* ",
    " *Hiç toplum içindeyken burnunu karıştırdın mı?* ",
    " *Gece geç saatte yaptığın en utanç verici şey nedir?* ",
    " *Çıplak olmak mı yoksa düşündüğün her şeyin tişörtünde yazması mı? Hangisini seçerdin?* ",
    " *Hiç havuza işeyip hiçbir şey olmamış gibi davrandın mı?* ",
    " *Sence bu grupta en kötü giyinen kişi kimdir?* ",
    " *Bu odadaki insanlardan kiminle hayatını değiştirmek isterdin? Neden?* ",
    " *Tuvalete oturduğun zaman ne düşünürsün?* ",
    " *Yaptığında utanmana neden olan mahcup zevkin nedir?* ",
    " *Burnunu karıştırır mısın?* ",
    " *En utanç verici anın neydi?* ",
    " *Hiç sınıfta yüksek sesle osurdun mu?* ",
    " *Hiç seksi bir fotoğrafını çekmeyi denedin mi?* ",
    " *Gizli aşkın kim?* ",
    " *Yapmaman gereken bir şeyi yaparken hiç yakalandın mı? Eğer yakalandıysan yaptığın şey ne?* ",
    " *Bu odadaki en seksi kişi sence kim?* ",
    " *Mevcut sevgilinle evleneceğini düşünüyor musun?* ",
    " *Kimsenin senin hakkında bilmediği şey nedir?* ",
    " *Hiç izlememen gereken bir film izledin mi? İzlediysen adı ne?* ",
    " *Yaptığın en yasa dışı şey neydi?* ",
    " *Kardeşini 1 milyon TL karşılığında başka bir kardeşle değişir misin?* ",
    " *Birden fazla kişiyle evlenme şansın olsa kimleri seçerdin?* ",
    " *Sence bu gruptaki en kötü insan kim olabilir?* ",
    " *Sevgilinden ayrılman için birisi sana 1 milyon TL verse ayrılır mıydın?* ",
    " *Sevgilin seni hiç utandırdı mı? Utandırdıysa o nedir?* ",
    " *Hiç sevgilini aldatmayı düşündün mü?* ",
    " *Hiç birini gözetlerken yakalandın mı?* ",
    " *Hiç burnunu karıştırırken yakalandın mı?* ",
    " *Hiç sosyal medyada pişman olduğun bir şey paylaştın mı? Paylaştıysan konusu ne?* ",
    " *Duşta işiyor musun?* ",
    " *Çorabını değiştirirken ayağını koklar mısın?* ",
    " *Hayatının en utanç verici anı neydi?* ",
    " *Birisi sana dünyanın en zengini olmayı teklif etse bile asla yapmayacağın şey nedir?* ",
    " *Bu gruptan kiminle sevgili olmak isterdin?* ",
    " *Sence bu grupta yer alan ve en kötü sevgili olacak kişi kimdir?* ",
    " *Hiç sevgilinin arkadaşına aşık oldun mu?* ",
    " *Hayatında yaptığın en kaba şey neydi?* ",
    " *Birine yaptığın en iğrenç şaka neydi?* ",
    " *Sevgilinle yapmak istediğin en çılgınca şey nedir?* ",
    " *Bir başkasından etkilenerek yaptığın en çılgınca şey neydi?* ",
    " *Çıplak kalmak veya aklından geçenlerin kafanın üstünde yazması arasında bir seçim yapmak zorunda olsan hangisini seçerdin?* ",
    " *Daha önce hiç sümüğünün tadına baktın mı?* ",
    " *Tuvalette otururken düşündüğün bazı şeyler nelerdir?* ",
    " *Bir parçası olduğun en utanç verici durum neydi?* ",
    " *En utanç verici alışkanlığın nedir?* ",
    " *Daha önce hiç altına işediğin oldu mu?* ",
    " *İnsanların içindeyken en utandığın an neydi?* ",
    " *İnsanlara ters gelmesine rağmen yapmaktan en büyük keyif aldığın şey nedir?* ",
    " *Gizliden gizliye ilgi duyduğun kişi kim?* ",
    " *Görünümünü 1-10 arasında nasıl değerlendirirsin?* ",
    " *Hiç yanlışlıkla bir arkadaşının sırrını ortaya çıkardın mı? Çıkardıysan o nedir?* ",
    " *Şu anki kız arkadaşınla/erkek arkadaşınla evleneceğini düşünüyor musun?* ",
    " *Hiç kulak kirinin tadına baktın mı?* ",
    " *Hiç terinin tadına baktın mı?* ",
    " *Bu grupta yer alan ve tanıdığın en kötü kişi olduğuna inandığın kişi kim?* ",
    " *Sevdiğiniz birinin önünde söylediğiniz veya yaptığınız en utanç verici şey nedir?* ",
    " *Gerçek dışı olan en büyük korkun nedir?* ",
    " *Aşık olduğun kişinin önünde en çok utandığın zaman ne zamandı?* ",
    " *Yatağını en son ne zaman ıslattın?* ",
    " *Kimsenin bilmediği en büyük sırrın nedir?* ",
    " *Kendini seksi yapmak için ne yaparsın?* ",
    " *Seni en çok ne tahrik eder?* ",
    " *Başka birinin kız arkadaşıyla çıkabilecek olsaydın bu kim olurdu?* ",
    " *Aşık olduğun kişiye sınır tanımadan bir mesaj gönderecek olsaydın bu ne olurdu?* ",
    " *Bu gruptan bir kişiyle evlenmek isteseydin bu kim olurdu?* "
]
        zorrsoru=random.choice(rzor)
        if member:
            await ctx.send(f'{member.mention} {zorrsoru}')
        else:
            if ctx.message.reference:
                replied_message = await ctx.fetch_message(ctx.message.reference.message_id)
                user = replied_message.author
                await ctx.send(f'{user.mention} {zorrsoru}')
            else:
                await ctx.send(f'{ctx.author.mention} {zorrsoru}')
async def setup(bot):
    await bot.add_cog(GetUsername(bot))
